In [22]:
import speech_recognition as sr
r = sr.Recognizer()
audio = False

with sr.AudioFile("oprah.wav") as source:
    audio = r.record(source)
try:
    s = r.recognize_google(audio)
    print("Text: "+s)
except Exception as e:
    print("Exception: "+str(e))

Text: empowerment is Authority it is a signed permission slip to actually seize the day it's the process of getting stronger and more confident and more engaged and to be empowered is to move through the world without any kind of fear or any kind of apology and with these gifts comes and even deeper privilege I believe and that is the ability to take charge of your own life to own yourself and clean your right and here's what I know for sure that to how much is given much is expected and I have been given so much I've earned it I've been blessed with it but I've been giving a lot and that's why I've chosen to use my life to lift other people up if things go wrong you hit a dead end as you will it's just life's way of saying time to change course so ask every failure this is what I do every failure every crisis every time I say what is this here to teach me and as soon as you get the lesson you get to move on if you really get the message to give you some remedial work


In [54]:
import numpy as np
import soundfile as sf

# Function to detect silent regions in audio array
def detect_silence(audio_array, threshold=0, min_silence_duration=100):
    silent_regions = []
    start_idx = None
    for idx, sample in enumerate(audio_array):
        if abs(sample).all() < threshold:
            if start_idx is None:
                start_idx = idx
        elif start_idx is not None:
            duration = idx - start_idx
            if duration >= min_silence_duration:
                silent_regions.append((start_idx, idx))
            start_idx = None
    if start_idx is not None:
        silent_regions.append((start_idx, len(audio_array)))
    return silent_regions

# Function to split audio array at silent regions
def split_audio_at_silence(audio_array, silent_regions):
    audio_chunks = []
    for start, end in silent_regions:
        audio_chunks.append(audio_array[start:end])
    return audio_chunks

# Load the WAV audio file
audio_array, sample_rate = sf.read("watts_cropped.wav")

# Detect silent regions in the audio
silent_regions = detect_silence(audio_array, threshold=1, min_silence_duration=2)

# Split the audio at silent regions
audio_chunks = split_audio_at_silence(audio_array, silent_regions)
audio_chunks

# # Optionally, save each chunk as a separate WAV file
# for i, chunk in enumerate(audio_chunks):
#     sf.write(f"chunk_{i}.wav", chunk, sample_rate)


[array([[0., 0.],
        [0., 0.]]),
 array([[0., 0.],
        [0., 0.]]),
 array([[0., 0.],
        [0., 0.]]),
 array([[0., 0.],
        [0., 0.]]),
 array([[0., 0.],
        [0., 0.]]),
 array([[0., 0.],
        [0., 0.]]),
 array([[0., 0.],
        [0., 0.]]),
 array([[0., 0.],
        [0., 0.]]),
 array([[0., 0.],
        [0., 0.]]),
 array([[0., 0.],
        [0., 0.]]),
 array([[0., 0.],
        [0., 0.]]),
 array([[0., 0.],
        [0., 0.]]),
 array([[0., 0.],
        [0., 0.]]),
 array([[0., 0.],
        [0., 0.]]),
 array([[0., 0.],
        [0., 0.]]),
 array([[0., 0.],
        [0., 0.]]),
 array([[0., 0.],
        [0., 0.]]),
 array([[0., 0.],
        [0., 0.]]),
 array([[0., 0.],
        [0., 0.]]),
 array([[0., 0.],
        [0., 0.]]),
 array([[0., 0.],
        [0., 0.]])]

In [71]:
import sys
from pydub import AudioSegment
from pydub.silence import split_on_silence

if len(sys.argv) < 2:
    print("No WAV file in input.")
    exit(0)

# Load your audio.
song = AudioSegment.from_wav('watts_cropped.wav')

# the imported function.
chunks = split_on_silence (
    # Use the loaded audio.
    song, 
    # Specify that a silent chunk must be at least 2 seconds or 2000 ms long.
    min_silence_len=2000,
    # Consider a chunk silent if it's quieter than -16 dBFS.
    # (You may want to adjust this parameter.)
    silence_thresh=-40
)

# Process each chunk with your parameters
for i, chunk in enumerate(chunks):
    # Create a silence chunk that's 0.5 seconds (or 500 ms) long for padding.
    silence_chunk = AudioSegment.silent(duration=500)

    # Add the padding chunk to the beginning and end of the entire chunk.
    audio_chunk = silence_chunk + chunk + silence_chunk

    # Export the audio chunk with new bitrate.
    print("Exporting chunk{0}.wav.".format(i))
    audio_chunk.export(
        "./chunk{0}.wav".format(i),
        format="wav"
    )


Exporting chunk0.wav.
Exporting chunk1.wav.
Exporting chunk2.wav.
Exporting chunk3.wav.


In [72]:
# Process each chunk with speech recognition
for i, chunk in enumerate(chunks):
    # Export the chunk to a temporary WAV file
    chunk.export("temp.wav", format="wav")
    
    # Load the temporary WAV file
    with sr.AudioFile("temp.wav") as source:
        # Record the audio data from the file
        audio_data = recognizer.record(source)
    
    # Perform speech recognition
    try:
        text = recognizer.recognize_google(audio_data)
        print(f"Chunk {i+1} Text:", text)
    except sr.UnknownValueError:
        print(f"Chunk {i+1}: Google Speech Recognition could not understand audio")
    except sr.RequestError as e:
        print(f"Chunk {i+1}: Could not request results from Google Speech Recognition service; {e}")


Chunk 1 Text: let's suppose that you were able every night to dream Any Dream you wanted to
Chunk 2 Text: 75 years of time or any length of time you wanted to have
Chunk 3 Text: and you would naturally as you began on this adventure of dreams you would fulfill all your
Chunk 4 Text: 75 years of total pleasure each you would say wow that was pretty great
